# Generated by Django 5.1 on 2024-10-03 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friend',
            name='unique_friend_request',
        ),
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Denied'), (4, 'Deleted')], default=1),
        ),
        migrations.AddConstraint(
            model_name='friend',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 1), ('status', 2), _connector='OR'), fields=('origin', 'target'), name='unique_friend_request'),
        ),
    ]
