name: ft


services:
  init_db:
    image: python:3.12.4-slim
    volumes:
      - data:/app
    command: rm /app/.gitkeep

  db:
    image: postgres:16.3
    init: true
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - network
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env
    depends_on:
      - init_db

  web:
    container_name: django
    build: django
    init: true
    restart: unless-stopped
    expose:
      - 8000
    networks:
      - network
    volumes:
      - django_src:/app
      - static:/static
      - media:/media
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    container_name: nginx
    build: nginx
    init: true
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - network
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - web


volumes:
  django_src:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./django/src

  static:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./temp/static

  media:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./temp/media

  data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./temp/data


networks:
  network:
    name: network
    driver: bridge
