name: ft

services:
  django:
    container_name: django
    build:
      context: django
      args:
        DEV: ${DEV}
        HOSTNAME: ${HOSTNAME}
        ADMIN_MAIL: ${ADMIN_MAIL}
        DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
    expose:
      - 8000
    init: true
    networks:
      - network
    volumes:
      - django-src:/app
      - static-files:/static
      - media-files:/media
      - public-keys:/etc/ssl/certs/
      - private-keys:/etc/ssl/private/
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "python manage.py healthcheck || exit 1"]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 10s

  nginx:
    container_name: nginx
    build:
      context: nginx
      args:
        HOSTNAME: ${HOSTNAME}
    ports:
      - 4443:443
    init: true
    networks:
      - network
    volumes:
      - nginx-src:/usr/share/nginx
      - static-files:/static
      - media-files:/media
      - public-keys:/etc/ssl/certs/
      - private-keys:/etc/ssl/private/
    env_file:
      - .env
    depends_on:
      django:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -o /dev/null -s -w '%{http_code}' ${BASE_URL} | grep 200 || exit 1"]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 10s

  postgres:
    container_name: postgres
    build:
      context: postgres
      args:
        POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 5432:5432
    networks:
      - network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 10s

networks:
  network:
    name: network
    driver: bridge

volumes:
  django-src:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./django/src
  nginx-src:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./nginx/src
  static-files:
    driver: local
  media-files:
    driver: local
  postgres-data:
    driver: local
  public-keys:
    driver: local
  private-keys:
    driver: local
