name: ft

services:
  django:
    container_name: django
    build: django
    ports:
      - 8000:8000
    init: true
    networks:
      - network
    volumes:
      - django-src:/app
      - staticfiles:/app/static

  nginx:
    container_name: nginx
    build: nginx
    ports:
      - 80:80
    init: true
    networks:
      - network
    volumes:
      - staticfiles:/usr/share/nginx
    depends_on:
      - django

networks:
  network:
    name: network
    driver: bridge

volumes:
  django-src:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./django/src
  staticfiles:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./static
