name: ft

services:
  db:
    image: postgres:16.3
    init: true
    # restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    container_name: django
    build: django
    init: true
    # restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      - network
    volumes:
      - django-src:/app
    env_file:
      - .env
    depends_on:
      - db

  # nginx:
  #   container_name: nginx
  #   build: nginx
  #   ports:
  #     - 80:80
  #   init: true
  #   networks:
  #     - network
  #   volumes:
  #     - staticfiles:/usr/share/nginx
  #   depends_on:
  #     - web

networks:
  network:
    name: network
    driver: bridge

volumes:
  django-src:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./django/src
  postgres-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./data
  # staticfiles:
  #   driver: local
  #   driver_opts:
  #     type: 'none'
  #     o: 'bind'
  #     device: ./static
