# Generated by Django 5.1 on 2024-09-17 10:39

import django.core.validators
import ft_auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(3), ft_auth.validators.validate_alnum]),
        ),
    ]
