from games.routing import websocket_urlpatterns as games_websocket_urlpatterns
from chat.routing import websocket_urlpatterns as chat_websocket_urlpatterns

websocket_urlpatterns = games_websocket_urlpatterns + chat_websocket_urlpatterns
